basePath: /
definitions:
  main.Item:
    properties:
      Desc:
        type: string
      Name:
        type: string
      Price:
        type: number
      UID:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: Thi is a simple service fon an inventory system
  license: {}
  title: Inventory API
  version: "1.0"
paths:
  /inventory:
    get:
      description: Get all the inventory's items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
      summary: Get all the inventory's items
    post:
      consumes:
      - application/json
      description: Add a new item to the inventory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
      summary: Add a new item to the inventory
  /inventory/{uid}:
    delete:
      description: Delete an existing item from the inventory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
      summary: Delete an existing item from the inventory
    put:
      description: Update an existing item from the inventory
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Item'
            type: array
      summary: Update an existing item from the inventory
swagger: "2.0"
